from . import component  # drone,
from . import (
    battery,
    battery_strap,
    camera,
    component_types,
    connector,
    custom_part,
    frame,
    gps,
    loaders,
    motor,
    propeller,
    receiver,
    receiver_antenna,
    stack,
    vtx,
    vtx_antenna,
    vtx_kit,
)
